newline_style = "Auto"
reorder_imports = true
max_width = 100
hard_tabs = false
tab_spaces = 4
use_small_heuristics = "Default"
reorder_modules = true
remove_nested_parens = true
fn_args_layout = "Tall"
edition = "2018"
merge_derives = true
