[package]
name = "llvm"
version = "0.0.0"
authors = ["ehsanmok <ehsanmo1367@gmail.com>"]
edition = "2018"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0"] }
